### PR TITLE
fixed '\s' escape sequence and used 'black' to format Python code

### PR DESCRIPTION
**Pull request by slava92**
This PR fixes *two* lines of code in "match/Match.py". The rest of the changes are from running `black` formatting utility.
According to the latest version of Python doc [re.html#re.sub](https://docs.python.org/3/library/re.html#re.sub), the second argument of `re.sub` function allows only a limited set of escape characters. `Match.py` used `"\s"` escape in the second argument which is not legal escape anymore. This PR changes those to instances to be `"\\s"` instead.

### CODE REVIEW

**Review by desilinguist — APPROVED** [review]

**Comment by desilinguist** [comment]
> Hi! 👋🏻 So, this looks good to me 🎉 but the tests should have run on Travis CI. I

@dmnapolitano  we no longer use Travis since it's not free anymore. For other repos, we use GitLab CI (via mirrored repos) but for this repo, I suspect we can just use Github Actions? I will file an issue for this. 

In the meantime, @slava92 , can you run the tests manually and confirm that they pass? May be also add a new test for your change if that's appropriate?

**Comment by slava92** [comment]
Sure, I'll work on it.
I am pretty confident in the last changes since they've been tested as part of RFS unit- and topology- test runs.

> In the meantime, @slava92 , can you run the tests manually and confirm that they pass? May be also add a new test for your change if that's appropriate?

**Comment by slava92** [comment]
It doesn't fail when I run it manually as `nosetests -v test_match.py ` :

> ----------------------------------------------------------------------
> Ran 1 test in 15.173s
> 
> OK

It is unclear what additional test I can add to the existing suite.

**Comment by slava92** [comment]
The same `nosetests` command fails when I run it on `stable` branch (with no fixes of `"\s"` escapes):
> ERROR: test_match.test_match_full_sentences
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/private/NLP/match-env.Darwin/lib/python3.10/site-packages/nose/case.py", line 197, in runTest
 >    self.test(*self.arg)
>   File "/private/NLP/match/test_match.py", line 198, in test_match_full_sentences
>     eq_(gold_result, Match.match(test_text, test_sentence))
>   File "/private/NLP/match/match/Match.py", line 109, in match
>     to_match = untokenize(" ".join(word_or_token_list_to_match).strip())
>   File "/private/NLP/match/match/Match.py", line 154, in untokenize
>     step4 = re.sub(r' \\*([,:;?!%]+)$', r'\s*\\' + r"\1", step3)
>   File "/private/NLP/match-env.Darwin/lib/python3.10/site-packages/regex/regex.py", line 278, in sub
>     return pat.sub(repl, string, count, pos, endpos, concurrent, timeout)
>   File "/private/NLP/match-env.Darwin/lib/python3.10/site-packages/regex/regex.py", line 702, in _compile_replacement_helper
>     is_group, items = _compile_replacement(source, pattern, is_unicode)
>   File "/private/NLP/match-env.Darwin/lib/python3.10/site-packages/regex/_regex_core.py", line 1737, in _compile_replacement
 >    raise error("bad escape \\%s" % ch, source.string, source.pos)
> regex._regex_core.error: bad escape \s at position 2
> 
> ----------------------------------------------------------------------
> Ran 1 test in 0.004s
> 
> FAILED (errors=1)

**Comment by slava92** [comment]
> It looks like there are multiple tests in `test_match.py` so when does nose only print 1 test?

It is because there is only one `"test"` function that run all the actual tests.
`def test_match_full_sentences():`

**Comment by desilinguist** [comment]
Oh, I was looking at the `master` branch which has a lot more tests. @dmnapolitano what should we do here? Ignore the other tests? I guess they were added after 0.2.2? 

I also see a `develop` branch. It seems weird to have 3 branches - stable, master, and develop. 

@dmnapolitano I think @slava92 and I need some help from you here.

**Comment by dmnapolitano** [comment]
Ok, I'm starting to remember what's going on lol.  So `master` has version 0.3 but `stable` has 0.2.2 which is still in use by RFS.  I think I wanted there to be a branch that reflected what was the stable version/code used by RFS.

I think RFS should switch to using 0.3, but on the off chance that it can't for some reason, I'll make the changes for both 0.2.2 (0.2.2.1) and 0.3 (0.3.1) and then you guys can test with both packages 😄

**Review by dmnapolitano — APPROVED** [review]

**Pull request merged**
